### ISSUE TITLE
bot's 'message' event being fired from everywhere

### ISSUE THREAD

**Issue by amirh715** [saeedhei/node-telegram-bot-api-persian-language#1]
Hello... I'm trying to write a bot using this API. My problem is that all 'message' events are fired from anywhere in my code, even if the event is wrapped in an if statement. What is the solution to this problem? There are times that I want to fire a message event when the user is in a sub-section of the bot. How can I handle this? Thanks a lot...

**Comment by saeedhei** [comment]
<p dir='rtl' align='right'>
سلام شما مشکلتون حل شد؟
</p>

**Comment by amirh715** [comment]
سلام. خیر متاسفانه هنوز هم مشکل دارم. متوجه نمی شم که چطور باید با استفاده
از این API چند سطح مجزا رو ساخت تا جواب کاربر منجر به emit شدن بقیه ی
listener ها نشه.

**Comment by saeedhei** [comment]
Man ham hamin moshkel ro daram fekr mikinam library asli bayad tavasote admin update beshe, betore mesal man mikham payam karbar ro baraye modir befrestam amma hamash dar hale goosh dadane va chan payam ersal mikone, ke majboor shodam felan ba save kardan dar db va az `once` estefade konam ke yekbar payamo begire

**Comment by saeedhei** [comment]
<p dir='rtl' align='right'>
من با این کدی که نوشتم مشکلم یجورایی حل شد ببینید برا شمام حل میشه؟
اگر حل شد بهم خبر بدین مرسی
</p>

[Link](https://github.com/saeedhei/node-telegram-bot-api-message-receiver)
