### ISSUE TITLE
تبدیل شدن متن فارسی به علامت سوال

### ISSUE THREAD

**Issue by ramyarrk** [saeedhei/node-telegram-bot-api-persian-language#2]
سلام متن فارسی در ربات تبدیل میشه به ؟؟؟؟؟
راه حل این مشکل چیه؟

**Comment by saeedhei** [comment]
سلام نمونه کد شما چی هستش؟ اگه ازین کتابخانه استفاده 
 می کنید نباید مشکلی داشته باشید،
دقت کنید پروژتونو باید توسط نود جی اس ران کنید.
آموزش اجرای پروژه نود جی اس:
(https://code.visualstudio.com/docs/nodejs/nodejs-tutorial)

```js
bot.on('message', (msg) => {
  const chatId = msg.chat.id;

  // send a message to the chat acknowledging receipt of their message
  bot.sendMessage(chatId, 'سلام');
});
```

**Comment by ramyarrk** [comment]
من از ویژوال استودیو 2017 استفاده میکنم

bot.onText(/hi/, function ontext(msg) {
	const key = {
		reply_to_message_id: msg.message_id,
		reply_markup: JSON.stringify({
			keyboard: [
				['????'],
				['hi']
			]
		})
	};	
	bot.sendMessage(msg.chat.id, "??????", key);
});

**Comment by saeedhei** [comment]
الان شما در ویژوال استودیو علامت سوال تایپ کردی؟
یعنی مشکل فونته ویژوال هست، یک بار با اون کدی که من بالا برات فرستادم امتحان کن اگر درست بود مشکل فونت ویژوال هست که باید به تاپیک های بخش کرومیوم ویندوز یا ویژوال مراجعه کنی، باز اگر حل نشد بهم اطلاع بده

```js
bot.onText(/\/hi/, (msg) => {
// ...
});
```
 :پیشنهاد من 
Download Visual Studio Code:
(https://code.visualstudio.com/download)
