### ISSUE TITLE
جلوگیری از دریافت پیام های قبل ...

### ISSUE THREAD

**Issue by sajjad31** [saeedhei/node-telegram-bot-api-persian-language#3]
سلام 
با چه متودی میتونم پیام های که قبل از ران شدن ربات را دریافت نکنم !؟
نکتع : با روش 
update
 نوشتم رباتو

:مثلا 
ربات یک هفته خاموش بوده حاالا میخام ربات ران کنم خب تا ران شد میاد تمام پیام هایی که زمان خاموشی ارسال شده رو پردازش میکنه !

2- لطفا روش وبهوک رو هم اموزش بدید

**Comment by NabiKAZ** [comment]
شاید راه بهتری باشه ولی به عنوان یک تریک، میتونی تاریخ پیامهای رو با تاریخ لحظه‌ی جاری که روبات رو استارت زدی مقایسه کنی. اگر قبلتر از اون بودند، نادیده بگیره.

**Comment by saeedhei** [comment]
برای جلوگیری از دریافت پیام‌های قدیمی هنگام راه‌اندازی ربات تلگرام، می‌توانید از پارامتر offset در روش getUpdates استفاده کنید.  این تضمین می‌کند که فقط به‌روزرسانی‌هایی را دریافت می‌کنید که جدیدتر از شناسه به‌روزرسانی مشخص‌شده هستند.

```javascript
const TelegramBot = require('node-telegram-bot-api');
const token = 'YOUR_TELEGRAM_BOT_TOKEN';
const bot = new TelegramBot(token, {polling: true});

let offset = 0;

bot.on('polling_error', (error) => {
  console.error(`Polling error: ${error}`);
});

bot.on('polling', () => {
  bot.getUpdates({ offset: offset + 1 }).then((updates) => {
    updates.forEach((update) => {

      console.log(update.message.text);
      offset = update.update_id;
    });
  }).catch((error) => {
    console.error(`Error fetching updates: ${error}`);
  });
});
```

در این مثال، ما یک متغیر "offset" را حفظ می کنیم که پس از هر به روز رسانی دریافتی به روز می شود.  این افست تضمین می‌کند که شما فقط به‌روزرسانی‌هایی را با شناسه‌های بیشتر از افست فعلی دریافت می‌کنید، و به طور موثر پیام‌های قدیمی را فیلتر می‌کند.
